name: "Download or Login Issues"
description: "Problems with downloading games, Mods, or integrated packages, or logging into the official account"
labels: [· Bug, 新提交]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "Checklist"
    description: "Please check each item below and tick to confirm."
    options:
    - label: "**I have tried using other launchers, and other launchers do not have this problem.** If other launchers also have issues, it proves that the network environment is poor [（solution）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr), and it's not a PCL issue, please **do not** submit feedback. [Download HMCL](https://hmcl.huangyuhui.net/download)"
      required: false
    - label: "I am aware that most of these issues are caused by poor network environments, but I believe my problem may be caused by PCL, unrelated to the network environment."
      required: true
    - label: "I have searched on the [Issues page](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) and [Common & Hard-to-Check Feedback and Issue List](https://github.com/Hex-Dragon/PCL2/discussions/1930) to confirm that this Bug has not been submitted before."
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: Description
    description: "Provide a detailed description of the specific manifestations of this Bug."
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: Reproduction Steps
    description: "Provide detailed steps on how to reproduce this Bug."
    value: |
      1、Click xxxx
      2、Scroll down, then click xxxx
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: Logs and Attachments
    description: "Upload Log1~5.txt from the PCL folder.[Where are the logs?](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-fvZW)"
    placeholder: "First click this text box, then drag and drop the file into the text box to upload."
  validations:
    required: true
