name: "Common Bug Feedback"
description: "Encountered other bugs not categorized here"
labels: [· Bug, 新提交]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "Checklist"
    description: "Please check each item below and tick to confirm."
    options:
    - label: "I have searched on the [Issues page](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) and [FAQ & Hard-to-Check Feedback and Issue List](https://github.com/Hex-Dragon/PCL2/discussions/1930) to confirm that this bug has not been submitted before."
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: Description
    description: "Provide a detailed description of the specific manifestations of this bug."
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: Reproduction Steps
    description: "Provide detailed steps on how to reproduce this bug."
    value: |
      1、Click xxxx
      2、Scroll down, then click xxxx
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: Logs and Attachments
    description: "Upload Log1~5.txt from the PCL directory. [Where are the logs?](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-fvZW)"
    placeholder: "First click this text box, then drag and drop the file into the text box to upload."
  validations:
    required: true
