name: "Optimization Suggestions"
description: "Suggestions for minor optimizations or improvements to existing features"
labels: [· 优化, 新提交]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "Checklist"
    description: "Please check each item below and tick to confirm."
    options:
    - label: "I have searched on the [Issues page](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) and [FAQ & Hard-to-Check Feedback and Issue List](https://github.com/Hex-Dragon/PCL2/discussions/1930) to confirm that this suggestion has not been submitted before."
      required: true
    - label: "I have viewed the [Feature Voting Page](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/) and confirmed that this suggestion is not on the voting list."
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: Description
    description: "Provide a detailed description of what specific areas need optimization and how they should be improved."
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: Reason
    description: "Provide a detailed description of why this optimization is needed, which helps developers assess its priority."
    value: |
      (Example)
      This optimization allows me to more easily ...
      Without this optimization, I would have to something every time, making the operation very cumbersome.
  validations:
    required: true