name: "优化建议 | Optimizations & Suggestions"
description: | 
  对已有功能的小幅度优化或改进建议。
  Minor optimizations or improvement suggestions for existing features.
labels: [· 优化, 新提交]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: 检查项 Checklist
    description: |
      请逐个检查下列项目，并勾选确认。
      Please review each of the following items individually and check to confirm.
    options:
    - label: |
        我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
        I have searched the [Issues page](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) and the [Common & Hard-to-Diagnose Feedback and Issue List](https://github.com/Hex-Dragon/PCL2/discussions/1930) to confirm that this suggestion has not been submitted before.
      required: true
    - label: |
        我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
        I have checked the [Feature Voting page](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/), and confirmed that this suggestion is not on the voting list.
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述 Description
    description: |
      详细描述具体需要优化哪些地方，要改成怎样的。
      Provide a detailed description of the areas that need optimization and how they should be improved.
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 原因 Reason
    description: |
      详细描述你为什么需要这项优化，这有助于开发者评估它的优先度。
      Provide a detailed explanation of why you need this optimization. This will help the developers assess its priority.
    value: |
      （示例）
      这项优化让我可以更方便地xxxx。
      如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。
      (Sample)  
      This optimization will allow me to do xxxx more conveniently.  
      Without this optimization, I have to xxxx every time, which makes the process cumbersome.
  validations:
    required: true