name: "新功能提案 | New Feature"
description: |
  对已有功能的大幅度修改，或添加一个新内容或选项。
  Major modifications to existing features, or the addition of new content or options.
labels: [· 新功能, 新提交]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: 检查项 Checklist
    description: |
      请逐个检查下列项目，并勾选确认。
      Please review each of the following items individually and check to confirm.
    options:
    - label: |
        我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
        I have searched the [Issues page](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) and the [Common & Hard-to-Diagnose Feedback and Issue List](https://github.com/Hex-Dragon/PCL2/discussions/1930) to confirm that this suggestion has not been submitted before.
      required: true
    - label: |
        我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。
        I have checked the [Feature Voting page](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/), and confirmed that this suggestion is not on the voting list.
      required: true
    - label: |
        我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……
        I understand that there are already too many new features yet to be developed, and it’s overwhelming, so new feature proposals are unlikely to be addressed. It’s also not recommended to submit new feature requests at this point. :(
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述 Description
    description: |
      详细描述你想添加的功能具体是怎样的。
      Provide a detailed description of the specific functionality you want to add.
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 原因 Reason
    description: |
      详细描述你为什么需要这项功能，这有助于开发者评估它的优先度。
      Provide a detailed explanation of why you need this feature. This will help the developers assess its priority.
    value: |
      （示例）
      我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
      (Sample)  
      I need this feature to xxxx. Many people have the need for xxxx, but without this feature, they won't be able to xxxx.
  validations:
    required: true